### ISSUE TITLE
Error: near line X: too many terms in compound SELECT

### ISSUE THREAD

**Issue by josephrocca** [dumblob/mysql2sqlite#1]
Trying to convert this `.sql` db:

https://sourceforge.net/projects/mysqlenglishdictionary/files/

And I'm getting these errors:

```
Error: near line 9: too many terms in compound SELECT
Error: near line 7129: too many terms in compound SELECT
Error: near line 14218: too many terms in compound SELECT
Error: near line 21284: too many terms in compound SELECT
Error: near line 28313: too many terms in compound SELECT
Error: near line 35612: too many terms in compound SELECT
Error: near line 42786: too many terms in compound SELECT
Error: near line 50057: too many terms in compound SELECT
Error: near line 57471: too many terms in compound SELECT
Error: near line 64757: too many terms in compound SELECT
Error: near line 71968: too many terms in compound SELECT
Error: near line 79414: too many terms in compound SELECT
Error: near line 86707: too many terms in compound SELECT
Error: near line 93873: too many terms in compound SELECT
Error: near line 101345: too many terms in compound SELECT
Error: near line 108689: too many terms in compound SELECT
```

I've got very little experience with this stuff, and notepad++ doesn't seem to like `.sql` files so I can't go to those line numbers (if they do indeed correspond to line numbers in the file).

Any ideas what's going on? Thanks for keeping this script alive!

**Comment by josephrocca** [comment]
Ah, okay, so it opened in notepad++, just took a while, and I think I see the problem. It inserts ~170k entries with only 15 lines. So the lines are really really long. Here's the start of one of the lines:

`INSERT INTO `entries` VALUES ('Magnificoes','pl. ','of Magnifico'),('Magnifico','n.','A grandee or nobleman of Venice; -- so called in\n   courtesy.'),('Magnifico','n.','A rector of a German university.'),('Magnifier','n.','One who .................`

So I imagine there's some inherent limit somewhere in `sqlite3`? Because I'm pretty sure that error message isn't coming from your script.

Any workarounds for something like this?

**Comment by josephrocca** [comment]
Unless you're interested in fixing this, you can close this issue - I've managed to find a plain text version of the db that I'll just manually parse. Cheers

**Comment by dumblob** [comment]
Well, this issue sounds quite interesting. The message is from sqlite3 and it should not appear as there are [no *select*](https://stackoverflow.com/questions/9527851/sqlite-error-too-many-terms-in-compound-select ) statements in the [sql file](https://sourceforge.net/projects/mysqlenglishdictionary/files/englishdictionary.sql/download ) you provided.

To make matters worse, I can't reproduce it with *sqlite 3.12.2* - it just works as expected:

~~~~
0$ time ~/del/mysql2sqlite.sh ~/del/englishdictionary.sql | sqlite3 ~/del/englishdictionary.sqlite
memory

real    1m1.109s
user    1m1.320s
sys     0m0.100s
0$ printf 'select * from entries limit 1;' | sqlite3 ~/del/englishdictionary.sqlite
A||The first letter of the English and of many other alphabets. The
   capital A of the alphabets of Middle and Western Europe, as also the
   small letter (a), besides the forms in Italic, black letter, etc., are
   all descended from the old Latin A, which was borrowed from the Greek
   Alpha, of the same form; and this was made from the first letter (/) of
   the Phoenician alphabet, the equivalent of the Hebrew Aleph, and itself
   from the Egyptian origin. The Aleph was a consonant letter, with a
   guttural breath sound that was not an element of Greek articulation;
   and the Greeks took it to represent their vowel Alpha with the a sound,
   the Phoenician alphabet having no vowel symbols.
0$ du -hsc ~/del/englishdictionary.sqlite
16M     /home/honza/del/englishdictionary.sqlite
16M     total
~~~~

Which version of sqlite are you using?

**Comment by josephrocca** [comment]
Oh that is strange. `sqlite3 --version` gives me: `3.8.2 2013-12-06 14:53:30 27392118af4c38c5203a04b8013e1afdb1cebd0d`

Maybe a bug introduced recently?

**Comment by dumblob** [comment]
Well, could you please try a newer version? Your version is already 2.5 years old, so in theory it might have this limitation. Let me know once you've tried it with a newer version.

**Comment by josephrocca** [comment]
Oh haha, I didn't even look at the date in that `--version` output. That's almost certainly the issue then. I'm on a windows machine right now - I'll wait til I can re-run it on linux. Thanks for your help
