### ISSUE TITLE
Can't export directly from MySQL server?

### ISSUE THREAD

**Issue by adjavaherian** [dumblob/mysql2sqlite#17]
So it looks like you can't export directly from the database anymore and you have to make a database dump before you export to sqlite?  I'm still using the older version of the script like so.  `./mysql2sqlite.sh -u root -p DB_20161218 | sqlite3 db.20161218.sqlite`

**Comment by dumblob** [comment]
Just use `-` (dash) instead of the file name to read from `stdin`. Running something like `mysqldump -u root -p DB_20161218 | ./mysql2sqlite - | sqlite3 db.20161218.sqlite` should do.

**Comment by dumblob** [comment]
Should you still have any issues, feel free to reopen this issue.

**Comment by BenoitDuffez** [comment]
There is now a check saying `file name - (dash) is not supported, because - means stdin` but in my opinion it should be removed.

Indeed, it effectively prevents the script from being piped after a `mysqldump` output; removing this check works as expected.

**Comment by dumblob** [comment]
@BenoitDuffez that's misunderstanding (see the code). You **can** use piping (e.g. `printf '%s\n' 'create table abc ();' | ./mysql2sqlite -`), but because `-` has this special meaning and `mysql2sqlite` doesn't support the `--` convention, you can't pass a file named `-` to `mysql2sqlite`.

**Comment by BenoitDuffez** [comment]
I was running `mysqldump ... | mysql2sqlite` and it failed about the file
being called `-`.

I removed the `exit` statement and it worked. So I guess there is still a
piping issue?

**Comment by dumblob** [comment]
`mysqldump ... | mysql2sqlite`

This is incorrect invocation. The error says, that `-` means stdin (standard input). See [my example above](https://github.com/dumblob/mysql2sqlite/issues/17#issuecomment-569951727 ).

**Comment by BenoitDuffez** [comment]
The point is, removing this block:

```

  if( ARGC != 2 ){
    printerr( \
      "USAGE: mysql2sqlite dump_mysql.sql > dump_sqlite3.sql\n" \
      "       file name - (dash) is not supported, because - means stdin")
    no_END = 1
    exit 1
  }
```

actually allows my incovation, which seems more natural. I don't see the point in explicitly using `-` as an argument as traditionally piping commands into another works well.

You wouldn't need `grep` to have an explicit `-` argument when piped, for example. Indeed:

```
some_command | grep 'pattern' -
```
vs

```
some_command | grep 'pattern'
```

The second is more natural, and I believe your script would be more usable without the need to explicitly mention `-` for stdin when being piped.

**Comment by dumblob** [comment]
@BenoitDuffez that's all true, but considering this script is being invoked from different languages and it's way easier to just call a binary instead of setting up yet another pipe, I'm not exactly sure it's a good idea to remove. Sure, currently one needs a pipe anyway because there is no way to specify output file, but that should be a backwards compatible addition - PRs welcome.

Historically the reason behind this part of code was also to provide a perfect builtin help, though this isn't perfect yet.

Third, as mentioned above, backwards compatibility is another thing to consider though probably not a stopper for a well-grounded decision.
