### ISSUE TITLE
Empty database? 

### ISSUE THREAD

**Issue by mdinh186** [dumblob/mysql2sqlite#19]
Not sure if I did it in the right way but it showed the line: memory  
after conversion is done. 
However, when open the file with sqlite3, it doesn't show any tables. Am I missing anything?

**Comment by dumblob** [comment]
I can't unfortunately tell what the issue might be from this sparse information. Could you please follow the instructions in https://github.com/dumblob/mysql2sqlite/issues/9#issuecomment-284164828 so that I can track down the issue? Thank you.
