### ISSUE TITLE
MIT Licence

### ISSUE THREAD

**Issue by esperlu** [dumblob/mysql2sqlite#2]
@dumblob: First I want to apologize for being sooo late to react to your request concerning the licence.  Of course I agree with my script being issued under the MIT Licence.

Tell me if this issue is enough to release my script under that licence or do I need to react on the original gist?

Thanks for your effort to improve the script.

**Comment by dumblob** [comment]
Hi @esperlu, great to hear you're back! Thank you very much for the approval of the MIT license.

Now, I'll enclose the history section in README with this your statement and a pointer to this issue and second I would kindly ask you to officially declare your gist as deprecated in a message in the gist discussion and add a pointer to this repository while closing the gist discussion to prevent someone else posting there.

I'll close this issue once the steps above are finished.

You're welcome to contribute to this repository!

**Comment by esperlu** [comment]
Hi dumblog,

Done. Thanks for taking that over.

Cheers.

Jean-Luc

**Comment by dumblob** [comment]
Thanks @esperlu.
