### ISSUE TITLE
Empty Database

### ISSUE THREAD

**Issue by underpope** [dumblob/mysql2sqlite#21]
I issued the following command to create my export file:

mysqldump -u root -p --skip-extended-insert --compact  my_db > huge.sql

When I HEAD and TAIL the huge.sql file, I see SQL commands as expected. It's a large file, something like 7.5 GB.

I tried to convert the file with mysql2sqlite:

./mysql2sqlite.sh huge.sql > yh.sql

Looks good so far; no errors generated. And when I execute HEAD and TAIL on the yh.sql file, I see regular SQL commands as expected.

But when I try importing yl.sql into yh.db using SQLiteBrowser, the resulting database is empty.

Am I missing something important? Besides the data, I mean. ;)

**Comment by dumblob** [comment]
Hm, sounds suspicious. Could you try to load `yh.sql` on the command line to an sqlite DB (e.g. using `sqlite3 huge.db < yh.sql`)?

You can also try to follow the [debugging hints](https://www.sqlite.org/debugging.html ) on the official page of sqlite (e.g. prepend `.eqp full` and `.echo on` using something along the line `{ printf '%s\n%s\n' '.eqp full' '.echo on'; yh.sql; } | sqlite3 huge.db`).

I didn't work with sqlitebrowser, but it might have some consequences (especially considering the size of the DB). sqlite3 itself is known to work well with DBs with hundreds of Gigabytes (of course on a bare disk without any filesystem or on a filesystem supporting large files).

**Comment by underpope** [comment]
I did end up loading yh.sql via the command line. Then I saved it to my
hard drive, and was finally able to open it with sqlitebrowser. Thanks for
responding.

**Comment by dumblob** [comment]
Well, then I would recommend opening an issue at https://github.com/sqlitebrowser/sqlitebrowser .
