### ISSUE TITLE
SQL error: SQL logic error or missing database

### ISSUE THREAD

**Issue by supersophie** [dumblob/mysql2sqlite#28]
Hi,

Thanks for the great programme. 

Noticed I had this when I piped into sqlite. Any ideas?

INSERT INTO `sessions` VALUES ('vvueta8ojr7e56m79ktvlqj935','redirect_to|s:180:"http://www.example.org/2012/05/23/android-market-device-restrictions/android-market-device-restrictions";',0,'2014-10-11 17:46:36',NULL);
SQL error: SQL logic error or missing database
CREATE TABLE `users` (
  `id` integer NOT NULL PRIMARY KEY AUTOINCREMENT
,  `login` varchar(64) DEFAULT ''
,  `password` varchar(60) DEFAULT ''
,  `full_name` varchar(250) DEFAULT ''
,  `email` varchar(128) DEFAULT ''
,  `website` varchar(128) DEFAULT ''
,  `group_id` integer DEFAULT '0'
,  `joined_at` datetime DEFAULT NULL
,  UNIQUE (`login`)
);
SQL error: SQL logic error or missing database

This is running on Debian Squeeze and libsqlite3-0  3.7.13-1~bpo60+1.

Best, Sophie

**Comment by dumblob** [comment]
Hm, I can't reproduce it and can't see any obvious issue with the SQL snippets you've posted. Could you please post a longer example of the SQL code (e.g. to pastebin) as well as the exact command you're using for the "piping into sqlite"? I also assume you're using the latest revision of mysql2sqlite script.

**Comment by supersophie** [comment]
I solved the problem by using sqlite3 on Debian 9 instead of Squeeze. The error was not there anymore

**Comment by dumblob** [comment]
Ok, good to know. Anyway, thanks for reporting.
