### ISSUE TITLE
\\\', is turned into \',

### ISSUE THREAD

**Issue by ibukanov** [dumblob/mysql2sqlite#33]
In string literals the sequence `\\\',` is turned into `\',` instead of the expected `\'',` . For example, the following MySQL:
```
INSERT INTO `texts` VALUES (18,'\\\',');
```
is converted into broken
```
INSERT INTO `texts` VALUES (18,'\',');
```

**Comment by MewX** [comment]
In my case, I replaced `([^\\])\\'` into `\1''` twice and it should solved most problems.

If you are unsure, you could simply run as many times as you want for this regex replace.

**Comment by dumblob** [comment]
Shall be solved with https://github.com/dumblob/mysql2sqlite/pull/34 .
