### ISSUE TITLE
PARTITION lines get transformed into lines with only ");"

### ISSUE THREAD

**Issue by Ramapitecus** [dumblob/mysql2sqlite#38]
Lines of the form 

```
/*!50100 PARTITION BY RANGE (YEAR(date))
(PARTITION p6 VALUES LESS THAN (2012) ENGINE = InnoDB,
 PARTITION p7 VALUES LESS THAN (2013) ENGINE = InnoDB)
```

end up as lines with only `);` which causes an error

sqlite 3.8.7.1
mysqldump  Ver 10.13 Distrib 5.5.59, for debian-linux-gnu (x86_64)

**Comment by dumblob** [comment]
`PARTITION` statements were not supported. I've committed a preliminary support for it by removing it. Feel free to try it out.

**Comment by Ramapitecus** [comment]
Hey, I have tested this and it works correctly. Thanks for you help.
