### ISSUE TITLE
Syntax Error in Cygwin

### ISSUE THREAD

**Issue by Suleman-Elahi** [dumblob/mysql2sqlite#40]
After following the instructions I encountered the following errors....... but the SQLite database is fine.....

![image](https://user-images.githubusercontent.com/24384996/43832671-ce66ed0a-9b25-11e8-9c1e-da30d0f5532c.png)

**Comment by dumblob** [comment]
Could you please post the content of the `test.sql` file (if it's large, then please use pastebin or similar).

**Comment by Suleman-Elahi** [comment]
Here it is : https://pastebin.com/CUwz88UR

I used PhpMyAdmin to generate the SQL dump.

**Comment by dumblob** [comment]
Yep, that's most probably the issue. Unfortunately only the `mysqldump` syntax is supported, but no other - see e.g. https://github.com/dumblob/mysql2sqlite/issues/9#issuecomment-284176392 . Could you please test it with `mysqldump` exactly as it's written in README.md?
