### ISSUE TITLE
Encrypt on export?

### ISSUE THREAD

**Issue by zocheyado** [dumblob/mysql2sqlite#47]
I am using this tool to help create an offline version for my web application. I use this script to generate a sqlite db, send it to my mobile device, restore it and connect to it. This is working great. I want to however add a layer of encryption so if this file ever is outside of my mobile app no one can access it. Is there a way with this tool or with sqlite3 to encrypt my database? Note that the MySQL database it is copied from does NOT have encryption.

**Comment by dumblob** [comment]
@zocheyado there is no support for encryption in any way in this tool, neither in sqlite3 itself. But you could change your mobile application DB backend to use some of the various enhanced versions of sqlite3 which do support encryption - see e.g. https://github.com/rindeal/SQLite3-Encryption , https://github.com/resilar/sqleet , https://github.com/sqlcipher/sqlcipher , https://github.com/OlivierJG/botansqlite3 , etc. and then generate an already encrypted DB.

**Comment by zocheyado** [comment]
Unfortunately the mobile application toolchain I am using does not support anything like that. Okay well thanks anyway!

**Comment by dumblob** [comment]
@zocheyado if the mobile application toolchain doesn't support changing of the DB backend, then there is a very last thing you can do - encrypt the DB yourself and let the application first decrypt the DB internally, save it temporarily, do the work and then again encrypt it when exporting.

On the server it would be something like `mysqldump | mysql2sqlite -  | sqlite3 mydb.db; openssl aes-256-cbc -in mydb.db -out mydb_encrypted.db -passin env:my_environ_var_with_password; rm -f -- mydb.db`.

**Comment by zocheyado** [comment]
While this would work if I was going to another linux server, it appears as if I cant run openssl decrypt either. I was assuming / hoping this was something built into sqlite. I am using EXPO and it appears as if there is no way to decrypt files without detaching. I cannot unzip, use openssl or any of those other sqlite replacements. I will figure something out.

**Comment by dumblob** [comment]
>I am using EXPO and it appears as if there is no way to decrypt files without detaching.

What do you mean by "detaching"? React (upon which is Expo based) supports modules - see e.g. https://stackoverflow.com/a/44652157 . That wouldn't do the job? The linked react library works internally exactly with AES-256-CBC, so I don't see any obstacle here. But of course, it's your choice :wink:.

**Comment by zocheyado** [comment]
Expo is built on-top of React but any modules that use native code (i.e your example) will only work in Expo if it is "[Detached](https://docs.expo.io/versions/v24.0.0/expokit/detach)" So while you are right that would work in react native, it won't work with expo which is a deal breaker for now. Still going to use this package for now, I can figure out encryption later, this works great ;)
