### ISSUE TITLE
Empty (or comment-only) lines with blank spaces make table import fail

### ISSUE THREAD

**Issue by francescozanoni** [dumblob/mysql2sqlite#55]
Hi,
the following table schema make table import fail:
````sql
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  -- <-- TWO BLANK SPACES BEFORE THE DASHES
  `username` varchar(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
````
This is what happens:
````bash
./mysql2sqlite users.sql | sqlite3 db.sqlite
memory
Error: near line 4: near ",": syntax error
````
The following one (no blank spaces), instead, works as expected:
````sql
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
-- <-- NO BLANK SPACES BEFORE THE DASHES
  `username` varchar(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
````
Am I doing anything wrong?

Thanks in advance.

Francesco

**Comment by dumblob** [comment]
Hi Francesco, did you use `mysqldump` to create the input SQL file? I'm asking as `mysql2sqlite` depends on the regularity of `mysqldump` output syntax.

**Comment by francescozanoni** [comment]
Yes, but I'm quite sure I added the new line on purpose, to increase the long statement readability by grouping fields by meaning.

**Comment by dumblob** [comment]
Then I have some bad news for you :cry: - as already pointed out above, we can support just `mysqldump` as we don't parse the whole MySQL syntax, but just a sole minimum to allow conversion of `mysqldump` dumps. Therefore we can't accommodate for any changes made to any *.sql file generated by `mysqldump`.

I would recommend adding the comments to the SQL file generated by `mysql2sqlite` instead.

Feel free to close this issue then :wink:.

**Comment by francescozanoni** [comment]
Oooooooh, yeah!
