### ISSUE TITLE
Help with simple conversion

### ISSUE THREAD

**Issue by donando101a** [dumblob/mysql2sqlite#56]
Someone please help me figure this out.  I have simplified my database dump to just three tables and I am running into problems when I try to create the sqlite database.  

I'm noticing that the CREATE statements are not being terminated with ';' and the "CREATE INDEX" statements are showing "" for the table names.  

The input seems simple enough that the script should be able to handle very easily, but I can't figure it out.

I'm running the script on Centos 7 with GNU AWK 4.0.2

============================================
Hi...here is my simplified input, created from mysqldump command:
============================================

PRAGMA foreign_keys = ON;
CREATE TABLE "applications" (
  "ID" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  "VERSION" varchar(255) NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "attribute" (
  "ID" varchar(255) NOT NULL,
  "NAME" varchar(255) NOT NULL,
  PRIMARY KEY ("ID")
);

CREATE TABLE "attributeinstance" (
  "ID" varchar(255) NOT NULL,
  "ATTRIBUTESETINSTANCE_ID" varchar(255) NOT NULL,
  "ATTRIBUTE_ID" varchar(255) NOT NULL,
  "VALUE" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("ID"),
  KEY "ATTINST_SET" ("ATTRIBUTESETINSTANCE_ID"),
  INDEX "ATTINST_ATT" ("ATTRIBUTE_ID"),
  CONSTRAINT "ATTINST_ATT" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "attribute" ("ID"),
  CONSTRAINT "ATTINST_SET" FOREIGN KEY ("ATTRIBUTESETINSTANCE_ID") REFERENCES "attributesetinstance" ("ID") ON DELETE CASCADE
);

================================
This is the output I get after running mysql2sqlite:
================================

PRAGMA synchronous = OFF;
PRAGMA journal_mode = MEMORY;
BEGIN TRANSACTION;
CREATE TABLE "applications" (
  "ID" varchar(255) NOT NULL
,  "NAME" varchar(255) NOT NULL
,  "VERSION" varchar(255) NOT NULL
,  PRIMARY KEY ("ID")
CREATE TABLE "attribute" (
  "ID" varchar(255) NOT NULL
,  "NAME" varchar(255) NOT NULL
,  PRIMARY KEY ("ID")
CREATE TABLE "attributeinstance" (
  "ID" varchar(255) NOT NULL
,  "ATTRIBUTESETINSTANCE_ID" varchar(255) NOT NULL
,  "ATTRIBUTE_ID" varchar(255) NOT NULL
,  "VALUE" varchar(255) DEFAULT NULL
,  PRIMARY KEY ("ID")
,
,  CONSTRAINT "ATTINST_ATT" FOREIGN KEY ("ATTRIBUTE_ID") REFERENCES "attribute" ("ID")
,  CONSTRAINT "ATTINST_SET" FOREIGN KEY ("ATTRIBUTESETINSTANCE_ID") REFERENCES "attributesetinstance" ("ID") ON DELETE CASCADE
);
CREATE INDEX "idx__" ON "" ();
CREATE INDEX "idx__" ON "" ();
CREATE INDEX "idx__" ON "" ("ATTRIBUTESETINSTANCE_ID");
CREATE INDEX "idx__" ON "" ("ATTRIBUTE_ID");
END TRANSACTION;

======================
This is the output from SQLITE3
======================

Error: near line 4: near "CREATE": syntax error
Error: near line 23: near ")": syntax error
Error: near line 24: near ")": syntax error
Error: near line 25: no such table: main.
Error: near line 26: no such table: main.

**Comment by dumblob** [comment]
On the first sight there might be 2 issues. But first, how exactly do you call mysqldump (which which parameters)? Based on your description, the setup of yours shall be supported by this conversion script.

**Comment by donando101a** [comment]
Thanks for looking at this and responding...this is my exact command:

mysqldump --no-data --default-character-set=utf8 --compatible=ansi --skip-extended-insert --compact -u<user> -p<password> mypetposdb >mypetposdb.sql

I'm starting to suspect the same thing, as i notice the table names are delimited by " (double quotes)...could this be a source of the problem?

**Comment by dumblob** [comment]
Yep, `--compatible=ansi` is most probably the culprit as we're expecting `mysqldump` to produce identifiers with backticks and not double quotes:
```
  if( match( $0, /`[^`]+/ ) ){
    tableName = substr( $0, RSTART+1, RLENGTH-1 )
  }
```
Could you try without `--compatible=ansi`?

**Comment by donando101a** [comment]
yeah!! that was it...worked like a charm without "--compatible=ansi"...I got 0 errors on about 40 tables and about 44 indexes....

Now I can focus on getting the data into my brand new sqlite database...

Thanks so much for this program and your help solving this problem.  Cheers!

**Comment by dumblob** [comment]
Great to hear it worked for you. Enjoy sqlite!
