### ISSUE TITLE
Syntax error near ","

### ISSUE THREAD

**Issue by sm8ps** [dumblob/mysql2sqlite#64]
mysql2sqlite fails with the following error:
```
./mysql2sqlite terra.sql | sqlite3 terra.db
memory
Error: near line 30013: near ",": syntax error
Error: near line 30015: near ",": syntax error
Error: near line 30017: near ",": syntax error
Error: near line 30018: near ",": syntax error
Error: near line 30024: near ",": syntax error
Error: near line 30027: near ",": syntax error
Error: near line 30028: near ",": syntax error
Error: near line 30030: near ",": syntax error
Error: near line 30031: near ",": syntax error
Error: near line 30033: near ",": syntax error
Error: near line 30035: near ",": syntax error
Error: near line 30037: near ",": syntax error
Error: near line 30038: near ",": syntax error
```
The issue happened on Ubuntu 19.10 with Sqlite3 v.2.8.17.
An online converter (https://www.rebasedata.com/convert-mysql-to-sqlite-online) did the job well. 
Since the SQL-dump is publicly available, I thought this might be a useful test case for the developers.
The database is available through the following link
https://www.inf-schule.de/content/1-information/4-datenbanksysteme/db/terra.zip
appearing in the following the online learning platform
https://www.inf-schule.de/information/datenbanksysteme/terra/selbstreferenz/uebungen

**Comment by sm8ps** [comment]
Some more information. And maybe I spoke too soon.
After importing the SQL-dump into MariaDB and dumping again with the suggested options ```--skip-extended-insert --compact```, mysql2sqlite converted the SQL-dump successfully to a Sqlite3 database.

Sorry if this looks obvious to some -- it wasn't to me at all. I think I close this issue.

**Comment by dumblob** [comment]
Correct, it would be enormous effort to support full syntax, so we stick with the assumption of `--skip-extended-insert --compact`. Glad it solved your issue :wink:.

Btw. I think you can definitely use some other converter available (if the terms & conditions for use are acceptable for you). T he main difference is, that all these to me known converters first load the DB into a proper MySQL DB sitting either on disk or in RAM and first then export it to SQLite using some wrapper - which is either very slow or very limited by RAM size. `mysql2sqlite` AWK script on the other hand doesn't do it this way, but rather convert it in a streaming fashing and thus can run blazing fast even on your wrist watches :wink:.

**Comment by sm8ps** [comment]
Thanks for the clarification! I much prefer a local script over some online service and I am happy that mysql2sqlite is available. In fact, the online converter did not respect data types and so the result was pretty useless.

Your explanation gave me a bit of insight into the technique used with Awk. That sounds really nifty. Gotta get me a wrist watch to try it out! wink
